#!/bin/bash

# Video compression script for DigitalVideo.mp4
# This will significantly reduce file size while maintaining quality

echo "======================================"
echo "Video Compression Guide"
echo "======================================"
echo ""
echo "Current video size: 8.0MB"
echo "Target size: ~2-3MB (60-70% reduction)"
echo ""
echo "To compress the video, you have several options:"
echo ""
echo "OPTION 1: Online Tool (Easiest)"
echo "  1. Go to https://www.freeconvert.com/video-compressor"
echo "  2. Upload public/DigitalVideo.mp4"
echo "  3. Settings:"
echo "     - Target size: 2-3 MB"
echo "     - Video codec: H.264"
echo "     - Audio: Remove (video is muted anyway)"
echo "     - Resolution: Keep original (1920x1080 or current)"
echo "     - Frame rate: 30 fps"
echo "  4. Download and replace the original file"
echo ""
echo "OPTION 2: Using ffmpeg (Best Quality)"
echo "  If you have ffmpeg installed locally, run:"
echo "  ffmpeg -i public/DigitalVideo.mp4 -c:v libx264 -crf 28 -preset slow \\"
echo "    -vf scale=-2:1080 -an -movflags +faststart \\"
echo "    public/DigitalVideo_compressed.mp4"
echo ""
echo "  Then replace:"
echo "  mv public/DigitalVideo.mp4 public/DigitalVideo_original.mp4"
echo "  mv public/DigitalVideo_compressed.mp4 public/DigitalVideo.mp4"
echo ""
echo "OPTION 3: Using HandBrake (GUI Tool)"
echo "  1. Download HandBrake: https://handbrake.fr/"
echo "  2. Open public/DigitalVideo.mp4"
echo "  3. Preset: 'Web' > 'Gmail Medium 3 Minutes 720p30'"
echo "  4. Video tab:"
echo "     - Framerate: 30 fps"
echo "     - Quality: RF 26-28"
echo "  5. Audio tab: Remove all audio tracks"
echo "  6. Save and replace original"
echo ""
echo "RECOMMENDED SETTINGS:"
echo "  - Remove audio (saves ~20-30%)"
echo "  - CRF 26-28 (good quality/size balance)"
echo "  - H.264 codec (best browser compatibility)"
echo "  - faststart flag (enables streaming)"
echo "  - Resolution: 1080p max (sufficient for web)"
echo ""
echo "======================================"
