import type { APIRoute } from 'astro';

const robotsTxt = `
User-agent: *
Allow: /
Allow: /services/
Allow: /services/it-consulting
Allow: /services/project-management
Allow: /services/business-intelligence
Allow: /services/process-automation
Allow: /use-cases/
Allow: /use-cases/enterprise-network-modernization
Allow: /use-cases/wordpress-migration-project
Allow: /use-cases/sales-analytics-logistics
Allow: /use-cases/erp-chatbot-integration
Allow: /user-story-template
Allow: /faq
Allow: /privacy-policy

# Crawl-delay for respectful crawling
Crawl-delay: 1

# Sitemap location (automatically generated by Astro)
Sitemap: ${new URL('sitemap-index.xml', import.meta.env.SITE).href}
`.trim();

export const GET: APIRoute = () => {
  return new Response(robotsTxt, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
    },
  });
};
